"""
Verifiable Research Agent – zero-cost core.

Uses Groq free tier + strict Pydantic contracts.
Designed so the same structure can later be migrated to full SymbolicAI
Expression + @contract decorators.
"""

from __future__ import annotations
import json
import os
from typing import Optional, Tuple
from groq import Groq
from tenacity import retry, stop_after_attempt, wait_exponential
from contracts import (
    ResearchQuestion,
    Claim,
    Source,
    ReportSection,
    VerifiedReport,
    ProvenanceTrace,
)

# Default free-tier friendly model
DEFAULT_MODEL = "llama-3.3-70b-versatile"


def get_client() -> Groq:
    key = os.getenv("GROQ_API_KEY")
    if not key:
        raise RuntimeError(
            "GROQ_API_KEY not set. Get a free key at https://console.groq.com "
            "(no credit card required) and put it in .env or Streamlit secrets."
        )
    return Groq(api_key=key)


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10))
def call_llm(system: str, user: str, model: str = DEFAULT_MODEL, temperature: float = 0.2) -> str:
    client = get_client()
    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        temperature=temperature,
        max_tokens=4096,
        response_format={"type": "json_object"},
    )
    return resp.choices[0].message.content or "{}"


SYSTEM_PROMPT = """You are a rigorous research assistant that follows Design-by-Contract principles.
You NEVER invent citations. Every factual claim MUST be backed by a plausible, real-looking source
(prefer real DOIs, arXiv IDs, or well-known review papers when possible; if uncertain mark confidence low).

You always answer in valid JSON that matches the requested schema exactly.
If you cannot find enough evidence, say so honestly in the limitations and lower confidence.
"""


def generate_verified_report(
    question: str,
    domain: Optional[str] = None,
    constraints: Optional[str] = None,
    model: str = DEFAULT_MODEL,
) -> Tuple[VerifiedReport, list[str]]:
    """
    Main entry point.
    Returns a fully validated VerifiedReport + list of intermediate log steps.
    Raises if final contract validation fails (after retries).
    """
    rq = ResearchQuestion(question=question, domain=domain, constraints=constraints)
    steps: list[str] = []
    steps.append(f"Input contract accepted: {rq.question[:80]}...")

    # Step 1 – Plan the research structure
    plan_prompt = f"""Research question: {rq.question}
Domain: {rq.domain or "general"}
Constraints: {rq.constraints or "none"}

Produce a JSON object with:
{{
  "sections": ["section title 1", "section title 2", ...],  // 2-5 focused sections
  "search_strategy": "brief description of how you will ground claims"
}}
"""
    plan_raw = call_llm(SYSTEM_PROMPT, plan_prompt, model=model)
    plan = json.loads(plan_raw)
    steps.append(f"Research plan created: {len(plan.get('sections', []))} sections")

    # Step 2 – Generate claims with forced provenance
    claims_prompt = f"""Research question: {rq.question}
Domain: {rq.domain or "general"}
Constraints: {rq.constraints or "prefer recent peer-reviewed sources"}
Planned sections: {json.dumps(plan.get("sections", []))}

Generate a JSON object:
{{
  "executive_summary": "3-6 sentence synthesis",
  "sections": [
    {{
      "title": "...",
      "summary": "optional short paragraph",
      "claims": [
        {{
          "text": "clear factual claim",
          "confidence": "high|medium|low",
          "caveats": "optional",
          "sources": [
            {{
              "title": "real or realistic paper/page title",
              "url_or_id": "DOI / arXiv / URL / ISBN",
              "year": 2023,
              "note": "optional relevance note"
            }}
          ]
        }}
      ]
    }}
  ],
  "limitations": "honest statement of gaps, possible biases, and what was not covered"
}}

Rules:
- Every claim MUST have at least one source.
- Prefer real known papers when you know them; otherwise use realistic identifiers and mark confidence low.
- Do not invent precise page numbers or fabricated DOIs that look real if you are unsure.
- Keep total claims between 4 and 12.
"""
    raw = call_llm(SYSTEM_PROMPT, claims_prompt, model=model, temperature=0.3)
    data = json.loads(raw)
    steps.append("Raw claims generated by LLM")

    # Step 3 – Build and validate under contract
    all_claims: list[Claim] = []
    sections: list[ReportSection] = []

    for sec_data in data.get("sections", []):
        sec_claims = []
        for c in sec_data.get("claims", []):
            sources = [Source(**s) for s in c.get("sources", [])]
            claim = Claim(
                text=c["text"],
                sources=sources,
                confidence=c.get("confidence", "medium"),
                caveats=c.get("caveats"),
            )
            sec_claims.append(claim)
            all_claims.append(claim)
        sections.append(
            ReportSection(
                title=sec_data["title"],
                claims=sec_claims,
                summary=sec_data.get("summary"),
            )
        )

    provenance = ProvenanceTrace(
        question=rq.question,
        model_used=model,
        steps=steps + ["Contract validation starting"],
        contract_checks_passed=False,
    )

    report = VerifiedReport(
        question=rq.question,
        executive_summary=data["executive_summary"],
        sections=sections,
        all_claims=all_claims,
        provenance=provenance,
        limitations=data.get("limitations", "Limitations not fully specified by model."),
    )

    # Final contract gate
    report.provenance.contract_checks_passed = True
    report.provenance.steps.append("All Design-by-Contract checks passed")
    steps.append("VerifiedReport contract satisfied")
    return report, steps
