"""
Verifiable Research Agent – zero-cost core.
"""

from __future__ import annotations
import json
import os
from typing import Optional, Tuple
from groq import Groq
from contracts import (
    ResearchQuestion,
    Claim,
    Source,
    ReportSection,
    VerifiedReport,
    ProvenanceTrace,
)

# Only use models that are confirmed available on free tier
DEFAULT_MODEL = "llama-3.1-8b-instant"


def get_client() -> Groq:
    key = os.getenv("GROQ_API_KEY")
    if not key:
        raise RuntimeError("GROQ_API_KEY not set. Add it in Streamlit Secrets.")
    return Groq(api_key=key)


def call_llm(system: str, user: str, model: str = DEFAULT_MODEL, temperature: float = 0.2) -> str:
    # Force a safe model no matter what the UI sends
    safe_models = {
        "llama-3.1-8b-instant",
        "llama-3.3-70b-versatile",
        "qwen/qwen3-32b",
        "moonshotai/kimi-k2-instruct",
    }
    if model not in safe_models:
        model = DEFAULT_MODEL

    client = get_client()
    try:
        resp = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=temperature,
            max_tokens=4096,
            response_format={"type": "json_object"},
        )
        return resp.choices[0].message.content or "{}"
    except Exception as e:
        raise RuntimeError(f"Groq API error: {type(e).__name__}: {str(e)}") from e


SYSTEM_PROMPT = """You are a rigorous research assistant that follows Design-by-Contract principles.
You NEVER invent citations. Every factual claim MUST be backed by a plausible source.
You always answer in valid JSON that matches the requested schema exactly.
"""


def generate_verified_report(
    question: str,
    domain: Optional[str] = None,
    constraints: Optional[str] = None,
    model: str = DEFAULT_MODEL,
) -> Tuple[VerifiedReport, list[str]]:
    rq = ResearchQuestion(question=question, domain=domain, constraints=constraints)
    steps: list[str] = []
    steps.append(f"Input contract accepted: {rq.question[:80]}...")

    plan_prompt = f"""Research question: {rq.question}
Domain: {rq.domain or "general"}
Constraints: {rq.constraints or "none"}

Produce a JSON object with:
{{
  "sections": ["section title 1", "section title 2"],
  "search_strategy": "brief description"
}}
"""
    plan_raw = call_llm(SYSTEM_PROMPT, plan_prompt, model=model)
    plan = json.loads(plan_raw)
    steps.append(f"Research plan created: {len(plan.get('sections', []))} sections")

    claims_prompt = f"""Research question: {rq.question}
Domain: {rq.domain or "general"}
Constraints: {rq.constraints or "prefer recent peer-reviewed sources"}
Planned sections: {json.dumps(plan.get("sections", []))}

Generate a JSON object:
{{
  "executive_summary": "3-6 sentence synthesis",
  "sections": [
    {{
      "title": "...",
      "summary": "optional short paragraph",
      "claims": [
        {{
          "text": "clear factual claim",
          "confidence": "high|medium|low",
          "caveats": "optional",
          "sources": [
            {{
              "title": "paper or page title",
              "url_or_id": "DOI / arXiv / URL",
              "year": 2023,
              "note": "optional"
            }}
          ]
        }}
      ]
    }}
  ],
  "limitations": "honest statement of gaps"
}}

Rules:
- Every claim MUST have at least one source.
- Prefer real known papers when possible; otherwise use realistic identifiers and mark confidence low.
- Keep total claims between 4 and 10.
"""
    raw = call_llm(SYSTEM_PROMPT, claims_prompt, model=model, temperature=0.3)
    data = json.loads(raw)
    steps.append("Raw claims generated by LLM")

    all_claims: list[Claim] = []
    sections: list[ReportSection] = []

    for sec_data in data.get("sections", []):
        sec_claims = []
        for c in sec_data.get("claims", []):
            sources = [Source(**s) for s in c.get("sources", [])]
            claim = Claim(
                text=c["text"],
                sources=sources,
                confidence=c.get("confidence", "medium"),
                caveats=c.get("caveats"),
            )
            sec_claims.append(claim)
            all_claims.append(claim)
        sections.append(
            ReportSection(
                title=sec_data["title"],
                claims=sec_claims,
                summary=sec_data.get("summary"),
            )
        )

    provenance = ProvenanceTrace(
        question=rq.question,
        model_used=model,
        steps=steps + ["Contract validation starting"],
        contract_checks_passed=False,
    )

    report = VerifiedReport(
        question=rq.question,
        executive_summary=data["executive_summary"],
        sections=sections,
        all_claims=all_claims,
        provenance=provenance,
        limitations=data.get("limitations", "Limitations not fully specified."),
    )

    report.provenance.contract_checks_passed = True
    report.provenance.steps.append("All Design-by-Contract checks passed")
    steps.append("VerifiedReport contract satisfied")
    return report, steps
